stages:
  - test
  - infrastructure  # Add infrastructure stage if applicable

# SonarCloud Job (if you want to include it)
sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]  # Clear the default entrypoint
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache  # Cache for SonarCloud analysis
  script:
    - sonar-scanner  # Run SonarCloud scanner
  only:
    - merge_requests
    - master
    - main

# OWASP ZAP Dynamic Security Test Job
zap_scan:
  stage: test
  image: owasp/zap2docker-stable  # Use the OWASP ZAP image
  script:
    - export TARGET_URL="http://localhost:5000/"  # Set the target URL
    - zap.sh -cmd -quickurl $TARGET_URL -quickout zap_report.html  # Run a quick scan and generate a report
  artifacts:
    paths:
      - zap_report.html  # Save the scan report as an artifact
  only:
    - master
    - main