stages:
  - test
  - infrastructure  # Ensure the infrastructure stage is added

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Location of the analysis task cache
  GIT_DEPTH: "0"  # Ensures all branches are fetched for Sonar analysis

# SonarCloud Job
sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]  # Clear the default entrypoint
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache  # Cache for SonarCloud analysis
  script:
    - sonar-scanner  # Run SonarCloud scanner
  only:
    - merge_requests  # Run on merge requests
    - master          # Run on the master branch
    - main            # Run on the main branch

# Terraform Apply Job
terraform_apply:
  stage: infrastructure
  image: hashicorp/terraform:light  # Using Terraform official image
  script:
    - terraform init -input=false   # Initialize Terraform
    - terraform plan -out=tfplan    # Generate execution plan
    - terraform apply -auto-approve tfplan  # Apply the execution plan
  only:
    - master  # Run on the master branch
    - main    # Run on the main branch
  before_script:
    - echo "Checking out 'main' branch..."
    - git fetch --all
    - git checkout main  # Ensure that the correct branch is checked out before applying Terraform
