stages:
  - test
  - infrastructure  # Added to match the terraform_apply stage

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Location of the analysis task cache
  GIT_DEPTH: "0"  # Ensures all branches are fetched for Sonar analysis

sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - main

terraform_apply:
  stage: infrastructure
  image: hashicorp/terraform:light
  script:
    - terraform init
    - terraform apply -auto-approve
  only:
    - master
    - main
