stages:
  - build
  - test
  - deploy

# Build the Docker image
build:
  script:
    - echo "Building the Docker image..."
    - docker --version   # Verify Docker is available
    - docker build -t my-docker-image .
  only:
    - master  # Can be changed to other branches or tags

# Test the Docker image
test:
  script:
    - echo "Running tests..."
    - docker run --rm my-docker-image # Example: Run the Docker image
  only:
    - master  # Can be changed to other branches or tags

# Deploy the Docker image
deploy:
  script:
    - echo "Deploying the Docker image..."
    - docker tag my-docker-image my-docker-image:latest
    - docker push my-docker-image:latest  # Push the image to Docker registry
  only:
    - master  # Can be changed to other branches or tags
