stages:
  - build
  - test
  - security_scan

# Build stage
build:
  stage: build
  image: ruby:3.1
  script:
    - apt-get update -y && apt-get install -y curl
    - curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose -f docker-compose.yml build

# Test stage (optional)
test:
  stage: test
  image: ruby:3.1
  script:
    - docker-compose -f docker-compose.yml up -d
    - sleep 10  # Wait for services to start
    - pytest tests  # Adjust this according to your testing framework
  services:
    - mysql:8.0

# Security Scan stage
security_scan:
  stage: security_scan
  image: owasp/zap2docker-stable
  script:
    - docker-compose -f docker-compose.yml up -d  # Start the application services
    - sleep 30  # Allow some time for the services to start
    - docker run --rm -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:5000 -g gen.conf -r zap_report.html
    - cat zap_report.html  # Display the generated report in the CI job log
  artifacts:
    paths:
      - zap_report.html
    expire_in: 1 week
  dependencies:
    - build
    - test
