stages:
  - test

# SonarCloud Job
sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]  # Clear the default entrypoint
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache  # Cache for SonarCloud analysis
  script:
    - sonar-scanner  # Run SonarCloud scanner
  only:
    - merge_requests
    - master
    - main

# ZAP Dynamic Security Test Job
zap_scan:
  stage: test
  script:
    # Start the ZAP server and perform a scan
    - java -jar zap.jar -daemon -port 8080 -host localhost
    - curl -X POST "http://localhost:8080/JSON/ascan/action/scan/?url=http://localhost:5000/&recurse=true&inScopeOnly=true"
    # Download and save the HTML report
    - curl -X GET "http://localhost:8080/OTHER/core/other/htmlreport/" -o zap_report.html
  artifacts:
    paths:
      - zap_report.html  # Save the ZAP report as an artifact
  only:
    - master
    - main
