stages:
  - build
  - scan
  - deploy

variables:
  DOCKER_IMAGE: devsecops-app:latest

# Build stage: Build the Docker image
build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .

# Scan stage: Run Trivy vulnerability scan
scan:
  stage: scan
  script:
    - echo "Running Trivy vulnerability scan"
    - trivy image $DOCKER_IMAGE

# Deploy stage: Deploy the app to Kubernetes
deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s-deployment.yaml
