image: sonarsource/sonar-scanner-cli:latest

stages:
  - build
  - test
  - sonar_analysis

sonar_analysis:
  stage: sonar_analysis
  script:
    - sonar-scanner -Dsonar.projectKey=devopsai_1 -Dsonar.host.url=http://localhost:9000 -Dsonar.login=squ_f4056395905746a36d8dd109253253b281508118
  only:
    - main
    - master
