image: 
  name: sonarsource/sonar-scanner-cli:11
  entrypoint: [""]

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  SONAR_HOST_URL: "http://localhost:9000"  # Replace with your SonarQube host URL
  SONAR_TOKEN: "sqp_261259031d20891e0ffc34a722ce32c3e5205abd"  # Replace with your SonarQube token
  SONAR_PROJECT_KEY: "devops_project1892352_devops_a29af4a0-016e-4fe8-ae2a-e657b6939fdf"  # Your project key

stages:
  - build
  - test
  - sonarqube-check
  - sonarqube-vulnerability-report

# Build stage (optional, if you have a build step)
build:
  stage: build
  image: niveditaj1/devsecops:latest
  script:
    - echo "Building the application..."
    - echo "Build complete!"

# SonarQube analysis
sonarqube_scan:
  stage: test
  image: sonarsource/sonar-scanner-cli:11
  script:
    - export SONAR_HOST_URL=$SONAR_HOST_URL
    - export SONAR_TOKEN=$SONAR_TOKEN
    - sonar-scanner \
        -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
        -Dsonar.sources=. \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN
  only:
    - master
    - main
    - develop

# SonarQube vulnerability report
sonarqube-vulnerability-report:
  stage: sonarqube-vulnerability-report
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=${SONAR_PROJECT_KEY}&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
  artifacts:
    expire_in: 1 day
    reports:
      sast: gl-sast-sonar-report.json
