stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  script:
    - echo "Building the project..."

test:
  script:
    - echo "Running tests..."

sonarqube:
  script:
    - echo "Installing SonarQube scanner..."
    - apt-get update && apt-get install -y wget unzip
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
    - unzip sonar-scanner-cli-4.8.0.2856-linux.zip
    - export PATH=$PATH:$PWD/sonar-scanner-4.8.0.2856-linux/bin
    - echo "Running SonarQube scan..."
    - sonar-scanner -Dsonar.projectKey=devopsai_1 -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqp_261259031d20891e0ffc34a722ce32c3e5205abd
  only:
    - main

deploy:
  script:
    - echo "Deploying the application..."
