stages:
  - build
  - test
  - deploy
build:
  script:
    - echo "Building the project..."
test:
  script:
    - echo "Running tests..."
deploy:
  script:
    - echo "Deploying the application..." modify this to build simple image in docker