stages:
  - build
  - test

# Build stage (optional, if you have a build step)
build:
  stage: build
  image: niveditaj1/devsecops:latest
  script:
    - echo "Building the application..."
    - echo "Build complete!"

# SonarQube analysis
sonarqube_scan:
  stage: test
  image: niveditaj1/devsecops:latest
  script:
    - export SONAR_HOST_URL="http://localhost:9000"  # Provided SonarQube host URL
    - export SONAR_TOKEN="sqp_261259031d20891e0ffc34a722ce32c3e5205abd"  # Provided SonarQube token
    - sonar-scanner \
        -Dsonar.projectKey="devops_project1892352_devops_a29af4a0-016e-4fe8-ae2a-e657b6939fdf" \  # Your SonarQube project key
        -Dsonar.sources="." \  # The directory where your source code is located
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN
  only:
    - master
    - main
    - develop
