stages:
  - test

# SonarCloud Job
sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]  # Clear the default entrypoint
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache  # Cache for SonarCloud analysis
  script:
    - sonar-scanner  # Run SonarCloud scanner
  only:
    - merge_requests
    - master
    - main

# ZAP Dynamic Security Test Job
zap_scan:
  stage: test
  image: openjdk:17-slim  # Use OpenJDK 17 slim image
  script:
    # Install curl in the slim image
    - apt-get update && apt-get install -y curl
    - echo "Starting ZAP in daemon mode..."
    - java -jar zap-2.15.0.jar -daemon -port 9090 -host 0.0.0.0 &
    - sleep 10  # Wait for ZAP to fully start
    - echo "Running security scan..."
    - curl -X POST "http://localhost:9090/JSON/ascan/action/scan/?url=http://localhost:3000/&recurse=true&inScopeOnly=true"
    - echo "Downloading HTML report..."
    - curl -X GET "http://localhost:9090/OTHER/core/other/htmlreport/" -o zap_report.html

  artifacts:
    paths:
      - zap_report.html
  only:
    - master
    - main



