stages:
  - test

# SonarCloud Job
sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]  # Clear the default entrypoint
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache  # Cache for SonarCloud analysis
  script:
    - sonar-scanner  # Run SonarCloud scanner
  only:
    - merge_requests
    - master
    - main

# ZAP Dynamic Security Test Job
zap_scan:
  stage: test
  image: openjdk:17-jre  # Using OpenJDK 17 Docker image (since you have OpenJDK 17)
  script:
    # Start the ZAP server with the specific jar file on port 9090
    - java -jar zap-2.15.0.jar -daemon -port 9090 -host localhost
    # Perform a security scan on the application running at localhost:3000
    - curl -X POST "http://localhost:9090/JSON/ascan/action/scan/?url=http://localhost:3000/&recurse=true&inScopeOnly=true"
    # Download the HTML report after the scan completes
    - curl -X GET "http://localhost:9090/OTHER/core/other/htmlreport/" -o zap_report.html
  artifacts:
    paths:
      - zap_report.html  # Save the ZAP report as an artifact
  only:
    - master
    - main



