stages:
  - build

# Docker-in-Docker service
services:
  - name: docker:19.03.12-dind
    alias: docker

# Image to run the job
image: docker:latest

# Variables
variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: "overlay2"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
  SONAR_HOST_URL: "http://localhost:9000"
  SONAR_TOKEN: "squ_f4056395905746a36d8dd109253253b281508118"

# Build the Docker image
build:
  stage: build
  script:
    - docker --version  # Check Docker version to verify it's available
    - docker build -t my-flask-app .
    - docker run -d -p 5000:5000 my-flask-app
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
